### ISSUE TITLE
How to reduce model size ?

### ISSUE THREAD

**Issue by delldu** [soushirou/stylegan3-encoder#4]
Dear friend,
    Work fine, but model size is almost 910M, it is hard to deployment. Would you have any good idea to reduce its size ?
Best Regards,

**Comment by hnp0411** [comment]
1. You may consider reducing the number of blocks of GradualStyleEncoder in training/networks_encoder.py, or using a lighter feature extractor network other than IR-SE50.
Current weights are trained with pixel2style2pixel structure. Changing the model architecture may result in poor result.
2. If you want to save memory while maintaining the structure now, implementing mixed presicion training seems to be a good choice.

**Comment by soushirou** [comment]
1. You may consider reducing the number of blocks of GradualStyleEncoder in training/networks_encoder.py, or using a lighter feature extractor network other than IR-SE50.
Current weights are trained with pixel2style2pixel structure. Changing the model architecture may result in poor result.
2. If you want to save memory while maintaining the structure now, implementing mixed presicion training seems to be a good choice.
